title: "CS7470 Fall23"
description: "Course webpage for CS7470, taught at Northeastern University by Steven Holtzen in Fall 2023"
theme: just-the-docs

url: 
baseurl: 

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
